export const defaultGrades = [
  // Singles
  { name: 'Singles', category: 'Kiwi Skate', segment: 'Free Skate' },
  { name: 'Singles', category: 'Pre Elementary Under 12', segment: 'Free Skate' },
  { name: 'Singles', category: 'Pre Elementary Girls 12 & Over', segment: 'Free Skate' },
  { name: 'Singles', category: 'Pre Elementary Boys 12 & Over', segment: 'Free Skate' },
  { name: 'Singles', category: 'Elementary Under 12', segment: 'Free Skate' },
  { name: 'Singles', category: 'Elementary Girls 12 & Over', segment: 'Free Skate' },
  { name: 'Singles', category: 'Elementary Boys 12 & Over', segment: 'Free Skate' },
  { name: 'Singles', category: 'Juvenile Under 12', segment: 'Free Skate' },
  { name: 'Singles', category: 'Juvenile Girls 12 & Over', segment: 'Free Skate' },
  { name: 'Singles', category: 'Juvenile Boys 12 & Over', segment: 'Free Skate' },
  { name: 'Singles', category: 'Basic Novice Girls', segment: 'Short Program' },
  { name: 'Singles', category: 'Basic Novice Girls', segment: 'Free Skate' },
  { name: 'Singles', category: 'Basic Novice Boys', segment: 'Short Program' },
  { name: 'Singles', category: 'Basic Novice Boys', segment: 'Free Skate' },
  { name: 'Singles', category: 'Intermediate Novice Girls', segment: 'Short Program' },
  { name: 'Singles', category: 'Intermediate Novice Girls', segment: 'Free Skate' },
  { name: 'Singles', category: 'Intermediate Novice Boys', segment: 'Short Program' },
  { name: 'Singles', category: 'Intermediate Novice Boys', segment: 'Free Skate' },
  { name: 'Singles', category: 'Advanced Novice Girls', segment: 'Short Program' },
  { name: 'Singles', category: 'Advanced Novice Girls', segment: 'Free Skate' },
  { name: 'Singles', category: 'Advanced Novice Boys', segment: 'Short Program' },
  { name: 'Singles', category: 'Advanced Novice Boys', segment: 'Free Skate' },
  { name: 'Singles', category: 'Junior Girls', segment: 'Short Program' },
  { name: 'Singles', category: 'Junior Girls', segment: 'Free Skate' },
  { name: 'Singles', category: 'Junior Boys', segment: 'Short Program' },
  { name: 'Singles', category: 'Junior Boys', segment: 'Free Skate' },
  { name: 'Singles', category: 'Senior Women', segment: 'Short Program' },
  { name: 'Singles', category: 'Senior Women', segment: 'Free Skate' },
  { name: 'Singles', category: 'Senior Men', segment: 'Short Program' },
  { name: 'Singles', category: 'Senior Men', segment: 'Free Skate' },
  
  // Adult Singles
  { name: 'Adult Singles', category: 'Bronze Women', segment: 'Free Skate' },
  { name: 'Adult Singles', category: 'Bronze Men', segment: 'Free Skate' },
  { name: 'Adult Singles', category: 'Silver Women', segment: 'Free Skate' },
  { name: 'Adult Singles', category: 'Silver Men', segment: 'Free Skate' },
  { name: 'Adult Singles', category: 'Gold Women', segment: 'Free Skate' },
  { name: 'Adult Singles', category: 'Gold Men', segment: 'Free Skate' },
  { name: 'Adult Singles', category: 'Elite Women', segment: 'Free Skate' },
  { name: 'Adult Singles', category: 'Elite Men', segment: 'Free Skate' },
  
  // Masters Singles
  { name: 'Masters Singles', category: 'Women', segment: 'Free Skate' },
  { name: 'Masters Singles', category: 'Men', segment: 'Free Skate' },

  // Ice Dance
  { name: 'Ice Dance', category: 'Juvenile', segment: 'Pattern Dance' },
  { name: 'Ice Dance', category: 'Intermediate', segment: 'Pattern Dance' },
  { name: 'Ice Dance', category: 'Basic Novice', segment: 'Pattern Dance' },
  { name: 'Ice Dance', category: 'Intermediate Novice', segment: 'Pattern Dance' },
  { name: 'Ice Dance', category: 'Advanced Novice', segment: 'Pattern Dance' },
  { name: 'Ice Dance', category: 'Advanced Novice', segment: 'Free Dance' },
  { name: 'Ice Dance', category: 'Junior', segment: 'Rhythm Dance' },
  { name: 'Ice Dance', category: 'Junior', segment: 'Free Dance' },
  { name: 'Ice Dance', category: 'Senior', segment: 'Rhythm Dance' },
  { name: 'Ice Dance', category: 'Senior', segment: 'Free Dance' },
  { name: 'Adult Ice Dance', category: 'Adult', segment: 'Pattern Dance' },
  { name: 'Adult Ice Dance', category: 'Adult', segment: 'Free Dance' },

  // Pairs
  { name: 'Pairs', category: 'Juvenile', segment: 'Free Skate' },
  { name: 'Pairs', category: 'Intermediate', segment: 'Free Skate' },
  { name: 'Pairs', category: 'Novice', segment: 'Free Skate' },
  { name: 'Pairs', category: 'Junior', segment: 'Short Program' },
  { name: 'Pairs', category: 'Junior', segment: 'Free Skate' },
  { name: 'Pairs', category: 'Senior', segment: 'Short Program' },
  { name: 'Pairs', category: 'Senior', segment: 'Free Skate' },
  { name: 'Adult Pairs', category: 'Adult', segment: 'Free Skate' },
  
  // Synchronized Skating
  { name: 'Synchronized Skating', category: 'Basic Novice', segment: 'Free Skate' },
  { name: 'Synchronized Skating', category: 'Mixed Age', segment: 'Free Skate' },
  { name: 'Synchronized Skating', category: 'Advanced Novice', segment: 'Free Skate' },
  { name: 'Synchronized Skating', category: 'Junior', segment: 'Short Program' },
  { name: 'Synchronized Skating', category: 'Junior', segment: 'Free Skate' },
  { name: 'Synchronized Skating', category: 'Senior', segment: 'Short Program' },
  { name: 'Synchronized Skating', category: 'Senior', segment: 'Free Skate' },
  { name: 'Synchronized Skating', category: 'Adult', segment: 'Free Skate' },
  
  // Showcase & Artistic Events
  { name: 'Individual Showcase', category: 'Beginner Mixed', segment: 'Performance' },
  { name: 'Individual Showcase', category: 'Beginner Women', segment: 'Performance' },
  { name: 'Individual Showcase', category: 'Beginner Men', segment: 'Performance' },
  { name: 'Individual Showcase', category: 'Intermediate Mixed', segment: 'Performance' },
  { name: 'Individual Showcase', category: 'Intermediate Women', segment: 'Performance' },
  { name: 'Individual Showcase', category: 'Intermediate Men', segment: 'Performance' },
  { name: 'Individual Showcase', category: 'Advanced Mixed', segment: 'Performance' },
  { name: 'Individual Showcase', category: 'Advanced Women', segment: 'Performance' },
  { name: 'Individual Showcase', category: 'Advanced Men', segment: 'Performance' },
  { name: 'Duet Showcase', category: 'Duet', segment: 'Performance' },
  { name: 'Group Showcase', category: 'Group', segment: 'Performance' },
  { name: 'Theatre on Ice', category: 'Theatre on Ice', segment: 'Performance' },
]
